### ISSUE TITLE
I want to create a custom walking routine

### ISSUE THREAD

**Issue by alejo9010** [Xian55/WowClassicGrindBot#111]
Hello, would really apreciate if you can point me in the right direction,
i want to create a custom profile, a little explanation, i wan to move to a fixed points lets say x 300 y 200, in that point i want to pull a mob, and then walk to another point x 500 x600 for example, and then start my rotation at that point, while facing to a fixed radiant, can you tell me where i should be looking to make this work ? thanks.

**Comment by Xian55** [comment]
Hey thanks for reaching out.

First of all, i would like to ask you to go thru the [Readme](https://github.com/Xian55/WowClassicGrindBot#readme) it should contain all the necessary info to bootstrap you and get a basic foundation how you can interact with the system.

> i want to create a custom profile
In this project we have two files which describes the behavior you would like to achieve.  All of them can be found under [Json](https://github.com/Xian55/WowClassicGrindBot/tree/main/Json)
- `ClassConfiguration` -> [Class](https://github.com/Xian55/WowClassicGrindBot/tree/main/Json/class) - describes a class related spell rotation and what spells to be used the given Requirement(s)/Conditions
- `Path` -> [Path](https://github.com/Xian55/WowClassicGrindBot/tree/main/Json/path) - describes what railway should follow

At this very moment there's no way to tell which radiant should the player is looking at the given Path point. The path inding will take care of what is the best direction to look at the given location in order to follow the path.

**Comment by alejo9010** [comment]
thanks for answering, but if u can elaborate a little more, as the project is really big and i dont know where to look lol
is possible, to go to point A, then stop pulling, go to point B, and kill mobs in that point without moving?

**Comment by Xian55** [comment]
> is possible, to go to point A, then stop pulling, go to point B, and kill mobs in that point without moving?

Such specific feature has not yet been implemented. As of this point you can't disable the targeting between waypoints.
The best you can do is to put certain mobs into blacklist.

**Comment by alejo9010** [comment]
ok i understand, can you point me to where the target/combat logic are in the source please? i want to add these features myself
and last question, you think its easy to move it from blazor to an actual winform ?

**Comment by Xian55** [comment]
> ok i understand, can you point me to where the target/combat logic are in the source please?

You can find the targeting in `FollowRouteGoal.cs` and the combat in `CombatGoal.cs`.


> you think its easy to move it from blazor to an actual winform ?

Im sure it would be a huge time investment to migrate all the current logic into winform.

**Comment by alejo9010** [comment]
ill look into it, thanks for answering

**Comment by alejo9010** [comment]
also, you know why my source breaks everytime i compile it for the first time and try to reopen it with visual studio? 
for example System.Drawing.Drawing2D start giving me  Drawing2D does not exist in System.Drawing namespace

**Comment by Xian55** [comment]
With the given info i'm unable to tell what exactly your problem so i could just guess a few
- Make sure to use the exact version of the nuget packages
- Clear/remove your local nuget packages
- Clear the build folder
- Build debug

**Comment by Xian55** [comment]
You can find everything in the `PlayerReader` and by finding references you can see where those values are exposed in the frontend.

You drifted away from the original issue. You can open an another one for winform. Closing this one.
