### ISSUE TITLE
Add some buffs of class Shaman

### ISSUE THREAD

**Issue by BillDong2021** [Xian55/WowClassicGrindBot#124]
hey sorry to bother you :) Is there any possible to add some buffs of shaman in Requirement? I dont know LUA language and addons at all :(  Thank you very much for your help! 

_Water Shield  ID:24398 
Shamanistic Focus  ID:43338_

Best regards

**Comment by Xian55** [comment]
I was unable to test it myself, if you could let me know if they work. ofc required English wow client.

**Comment by BillDong2021** [comment]
I tested the buff "Shamanistic Focus" just now but it cant work. I want to realize something like this: If I have the buff, then cast fire shock.  The icon in blazor website is always red even if i have the buff.  Whats the problem?

```
	  
        "Name": "Fire shock",
        "Key": "4",
        "Requirements": ["Mana%>40","TargetHealth%>10","Shamanistic Focus"],
        "Log": false,
	"Cooldown": 12,
        "MinMana": 200
      
```

**Comment by Xian55** [comment]
Are you using English wow client?

**Comment by BillDong2021** [comment]
Yes sure I used English wow client to test it yesterday. Maybe something wrong :(
BTW i see your recent commit says the addons now supports all available languages, does that mean the bot can run in other language wow client?

**Comment by BillDong2021** [comment]
I'll test #127 later. Thanks!!!

**Comment by Xian55** [comment]
It was my mistake actually to not check how the buff really works. because i foolishly put `Shamanistic Focus` into the checklist, however that's a talent actually or at least the player never gets it. However there's a sub spell called `Focused` and that's the one which get applied to the player.

https://tbc.wowhead.com/spell=43338/shamanistic-focus
https://tbc.wowhead.com/spell=43339/focused

**Comment by BillDong2021** [comment]
I didn't notice it at all either, I misled you. Anyway I guess it can perform correctly now. Thank you very much!
