### ISSUE TITLE
Blacklisted bugged 

### ISSUE THREAD

**Issue by alejo9010** [Xian55/WowClassicGrindBot#134]
i think i found the problem, is in tge pulltargetgoal,  the pullStart is not getting updated anywhere in the code, but im out of context since the change is new

so the PerformAction from PullTargetGoal, the first IF statement, is always true, so its always moving the camera for 1k ms

**Comment by Xian55** [comment]
Hey thanks for reaching out!

If you could attach your full logs it would be really helpful in order to determine what's going on.
On top of that if you could share the `ClassConfiguration` i may repro the case myself!

**Comment by Xian55** [comment]
Hey could you checkout https://github.com/Xian55/WowClassicGrindBot/tree/fix/local-pathing-issue and see if there's any improved?

**Comment by alejo9010** [comment]
thanks man that did the job and it feels like a lot better than before!, but i still have 1 more issues idk if i should create a new post? 
first, sometimes when it goes to pull a target, sometimes it would walk forward like 3 or 5 secs then turn around, like theres a little delay for it to detect that its in pull range or seomthing like that

**Comment by alejo9010** [comment]
gonna attach a log, so u can check when u have time, for the loot and the extra forward walk when pulling
[out20210927.log](https://github.com/Xian55/WowClassicGrindBot/files/7240226/out20210927.log)

**Comment by Xian55** [comment]
>thanks man that did the job and it feels like a lot better than before!

During the rework of the `CastingHandler` `PullTargetGoal` `CombatGoal` i've eliminated most of the `InteractKey` presses because there are two sides of the coin. 

 For melees its really good having as many Interact key presses as possible to make sure approaching the target and facing correctly is the main priority.
 
 However for ranged classes pressing more `InteractKey` then it's needed to be result reducing the gap between the target more quickly which is not ideal.
 
 So i would suggest to at this point to try combine more interact key in the combat goal and try to play with the `StopBeforeCast` KeyAction attribute

**Comment by alejo9010** [comment]
oh yeah your right, i made a hunter to test it and its alot better, i guess ill have to fine tune it for melees, but thanks, the pathing is like 2x better than before!
