### ISSUE TITLE
Feature request: Background mode

### ISSUE THREAD

**Issue by AsterNighT** [Xian55/WowClassicGrindBot#166]
I hope to run wow in background while still using the bot, so I can do other things at the same time. As far as I can see, despite from the two mouse input part(select npc and loot), all keyboard input can be handled in background. Selecting npc can be achieved by using `tab` only (though less accurately), and loot can be done with `target last target` and `interact` if not for skinning and herbing.

**Comment by Xian55** [comment]
Yes it is possible to use only the keyboard while running the app. The app can only function at best if it can use both the mouse and keyboard. There are few things what have to consider. 

It is a really red flag to send mouse and key events to the client while it sits in the background. I would say its not a normal way to play the game.

In case the mouse usage is prohibited, few features only works limited:
- Skinning is not possible, since after looting the target the `Target last target` keypress no longer select the same corpse.
- Incase multiple enemies engages the player only the last one killed could be looted.
- Friendly targeting (vendor/repair) only works with only keyboard mode while a macro is used to specify to target the npc.

**Comment by AsterNighT** [comment]
Yes. But for not-skin player who want exp only that's quite nothing. And for those who has two or more screens, it's very much necessary to use mouse on their second screen. Will it be a good idea to have an option to toggle that?

**Comment by Xian55** [comment]
Yes would be a great addition a background mode which only use keyboard and mouse is prohibited.
