### ISSUE TITLE
Bug: `CreatureHistory` Damage taken guid was unable to expire

### ISSUE THREAD

**Issue by jacobhamblin** [Xian55/WowClassicGrindBot#183]
### Description

Sometimes when running the bot, whether it be the moment I click start bot, or at some point during an otherwise successful run, the bot will just sit there spamming in console New Plan= NO PLAN and Waiting for water. This eventually leads to the character either sitting around until a mob spawns nearby or until he gets kicked for being afk. I've tried adjusting the profile to avoid the situation, but as far as I can tell the class profile doesn't affect it. That's what happens - I instead expect the character to recognize that it has full health / mana, is not in combat, has nothing to loot, and is ready to walk and find the next mob.

### Addon Version

1.1.42

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

1. Follow readme to install the bot
2. Select a mage profile (mage may be unrelated) and any profile I've tried so far
3. Start bot

For me, the behavior is seen within the first hour pretty consistently, though often much sooner than that.

### Screenshots

![no_plan_water](https://user-images.githubusercontent.com/7588474/143822943-216e893f-a740-45ca-bece-a073e09bd207.png)

### Logs

Probably multiple examples in the file, but there's one example at 20:03:57.834.

File's too big to upload here on github.

https://easyupload.io/2supzq

**Comment by Xian55** [comment]
:wave: Hey thanks for reaching out. 

At first glance it seems nothing is wrong with the `Water` KeyAction. As it the output says there are not suitable plan found.

Most likely the issue is somewhere along the `No Danger` GoalKey, probably mismanaging how the `damage taken unit GUID` is being handled in the `CreatureHistory`, and thus the `DamageTaken` list is not getting emptied... I will look at it soon, probably tomorrow. 

Until then i suggest to do these steps:
1. in-game:  type in chat `/reload` 
1. frontend: press `Init state` button
1. frontend: load the chosen profile

If that doesn't help, restart the application.
