### ISSUE TITLE
Setup: Not finding 100 data frames

### ISSUE THREAD

**Issue by TheGuyWhoBots** [Xian55/WowClassicGrindBot#188]
### Description

Hi,

I build with no issues but then when I get to the frame configuration stage it doesn't find all 100 data frames. I've tried multiple fresh installs / following the steps carefully and i'm having no luck. The dataframes appear very small compared to the original and it finds very few. They might be proper size for your version but that's all i can really say as i setup the original with no issues. I'm on a VM.

I've built / tested 2 versions of yours and same issue :/ 

### Addon Version

1.1.39

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

1) Build
2) Follow steps up until frame configuration
3) addon doesn't display all data frames needed

### Last Good Version

Original

### Screenshots

![Untitled](https://user-images.githubusercontent.com/45080367/146634892-42cd1eb3-f8cb-42bd-8771-2495eb17038b.png)

**Comment by TheGuyWhoBots** [comment]
I've tried 1.1.42 again and it's still not working
![1212](https://user-images.githubusercontent.com/45080367/146635520-5fe63342-b1c7-472e-8a9a-f9064d1bc43d.PNG)

**Comment by TheGuyWhoBots** [comment]
![4444444444](https://user-images.githubusercontent.com/45080367/146635607-edd83e4b-8bc5-45f2-b819-7474101968ca.PNG)

**Comment by Xian55** [comment]
:wave: Hello there! I'm glad you made contact about your issue.

It seems you still not using the latest version of the stack. Be sure to upgrade to the latest one from `dev` branch, and try with that.
https://github.com/Xian55/WowClassicGrindBot/blob/c3b1b685ff6a5e96ab39a1e94d9d033851eb0032/Addons/DataToColor/DataToColor.toc#L5

Other than that, as you said you been using virtual machine. Be sure to disable
* any resolution scaling
* any color management modifications

1. When ever you doing the `Frame Configuration` process, be sure to have a clear background behind the top left corner of the screen. like look at the sky or one of the nearby building which has the very same texture, that way you can avoid pixel bleeding effect.

Good example, to avoid color bleeding:
![image](https://user-images.githubusercontent.com/367101/146641774-4c6184a7-e48f-49d0-a6ed-6d5dc61137e7.png)

Bad example, you can see here the sky and trees are mixed up in the image which can be a problem.
![image](https://user-images.githubusercontent.com/367101/146641792-436e2b84-b192-405c-9ba8-5916bd277a28.png)

2. Data frame size
> The dataframes appear very small compared to the original
This one shouldn't be a problem, the reference image just for demonstrating purposes. Not meant to be the exact same result. Although you could can try tweaking the `CELL_SIZE` from `1` -> `3` the key is to be an odd number. In the original addon is under the https://github.com/Xian55/WowClassicGrindBot/blob/c3b1b685ff6a5e96ab39a1e94d9d033851eb0032/Addons/DataToColor/DataToColor.lua#L17
however in your machine you have to find your wow install location ex. `C:\Program Files (x86)\World of Warcraft\_classic_\Interface\AddOns\trying\trying.lua` since you named the addon as **trying**

**Comment by TheGuyWhoBots** [comment]
Hi, thanks for the reply! 

I got it working on my host machine without needing to change anything. I changed the cell size from 1 to 3 on the VM and got it working. Thank you! Do you have a discord group?

**Comment by Xian55** [comment]
Glad to hear that you got it working. Hard to tell what's causing the issue inside the VM, would require more info about the setup and settings.

Currently there are no open discord group. 

Have a gooday!
