### ISSUE TITLE
NPC Sell Infinite Loop Bug

### ISSUE THREAD

**Issue by TheGuyWhoBots** [Xian55/WowClassicGrindBot#190]
### Description

When you add in NPC Sell feature to your profile it infinite loops from start of path to vendor, then runs back to start then repeats.

### Addon Version

1.1.42

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

1) Add NPC Vendor option to your profile
2) Run it and see what happens.
3)Even when you hit "Stop" it continues.

### Last Good Version

1.1.42

**Comment by Xian55** [comment]
Hello there! Could you attach logs about the issue. Would speed up the investigation. Thanks 🙇

**Comment by TheGuyWhoBots** [comment]
Hi,

I checked my logs but I only have one from yesterday morning (my most recent, even though i've stopped/started the bot many times yesterday while i tweaked settings) I think it has something to do with BagsFull. Bags weren't full but it kept flagging true.

**Comment by Xian55** [comment]
When ever you start the application. Make sure to do the following steps in order to the inventory/actionbar/talents/spellbook getting properly extracted.

* Press `Init State` button twice. *Read down how to do it properly.*
* Select the desired class profile
* Press `Load Profile` button once.

Press `Init State` button once and wait for it finishes. You should see items pop up in the `Bag Changes` section. Then press the button again. The funky thing about this only happens in `Debug` build for some reason. Have to investigate what's going on.

As a result you should be able to count the in game item count and `Bag Items:` table in the frontend

![image](https://user-images.githubusercontent.com/367101/146860063-7ce4174e-cb54-4c2f-b581-1763e74504e1.png)

**Comment by TheGuyWhoBots** [comment]
Thanks! done what you said to do and it is finally running like normal with NPC sell added back in.

**Comment by Xian55** [comment]
Hey have you encountered the issue ever since?
