### ISSUE TITLE
AttendedGather Problems

### ISSUE THREAD

**Issue by horstc** [Xian55/WowClassicGrindBot#276]
### Description

Hi, I'm struggeling with the AttendedGather Mode. After freshly starting the bot and start the profile it will work as expected (mounts up and starts running the path), but if it finds a yellow dot on the minimap it will not stop the bot and keep running the path... also the youtube video is not starting to play. In the Blazor minimap I can see it recognized the node, drawing a red dot on it.

So I stop the Bot manually and gather, after that I press "Start Bot" again and the character starts jiggelin and jumping around, always saying "Trying to unstick" etc. also it's not mounting anymore. Stoping and starting the Bot does not change that. The Bot has to be completely restarted (kill process). Also the Blazor UI starts to not respond anymore.

regards
horstc

### Addon Version

1.2.4

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

1. Load Class Profile with AttendedGather Mode
2. Load Profile
3. Start Bot
4. Bot does not stop after finding a node to gather, so I stop manually
5. Start Bot again - it will not work anymore

### Logs

............
2022-04-20 22:14:20.632 +02:00 [INF] Bot thread stopped! <<<----- This is where I stopped it to gather manually
2022-04-20 22:14:46.701 +02:00 [INF] We seem to be stuck! <<<----- This is first line after pressing start again
2022-04-20 22:14:46.784 +02:00 [INF] Stuck for 26s, last tried to unstick 26s ago. Unstick seconds=26.
2022-04-20 22:14:46.786 +02:00 [INF] Trying to unstick by backing up for 4250ms
2022-04-20 22:14:51.063 +02:00 [INF] Trying to unstick by turning for 638ms
2022-04-20 22:14:51.703 +02:00 [INF] Trying to unstick by moving forward after turning for 202ms
2022-04-20 22:14:51.958 +02:00 [INF] Move to next point
2022-04-20 22:14:52.346 +02:00 [INF] We seem to be stuck!
2022-04-20 22:14:52.347 +02:00 [INF] Navigation: Clear route to waypoit since stucked for 31
............
this is going on endless

**Comment by Xian55** [comment]
Hello there, thanks for reaching out.

Since i started working on the project, haven't been tried out the `AttendedGather` mode. 

Most likely broke it with the extensive amount of refactor and rework. Sorry about that. Will look into it soon.

**Comment by horstc** [comment]
Thank you :) 

Also noticed, it won't defend itself if it get's attacked while running the path.

I also wondered if it would be possible to get this mode a bit more automated. Since the Bot know's the player coordinates and the position of the yellow dot on the minimap, it could calculate the coordinates of the node, then walk exactly to it and try to gather itself?

**Comment by Xian55** [comment]
At first i'm going to attempt to restore the original behavior of the `AttendedGather` mode, first and foremost.

> Also noticed, it won't defend itself if it get's attacked while running the path.

Will look into it as well what's going on.

> I also wondered if it would be possible to get this mode a bit more automated. Since the Bot know's the player coordinates and the position of the yellow dot on the minimap, it could calculate the coordinates of the node, then walk exactly to it and try to gather itself?

The idea sounds great, its a really interesting challenge to tackle, most of the time can't just use the straight path to gather the node, but have to actually take a path to get there. In my observation, some of the gatherable nodes placed in a really tricky location. Just recalling few locations at [Un'Goro Crater](https://classic.wowhead.com/ungoro-crater) 😓 

The `player coordinates` is (**float**)6 digit precise, could be more up to (**double**)12 digit - double precision, this part shouldn't be a problem. However the `yellow dot`(node) on the minimap is not that simple, since there are no available API to query those. Thus unable to gather precise location information. 

The best option i have with the current setup is to make some assumption and try to estimate it, bit side track here: 
In the past added a feature to estimate the killed mob corpse location, it does the job, but as of current standing only using it for direction - what direction the player should rotate after killing multiple enemies in a single fight, for skinning and looting incase there are no visible corpse npc name on the screen.

Back to the minimap node challenge, in order to get it working properly have to normalize the minimap display size, and the zoom level. For that probably going to be mandatory to use [BasicMinimap addon](https://www.curseforge.com/wow/addons/basic-minimap).

**Comment by horstc** [comment]
> However the yellow dot(node) on the minimap is not that simple, since there are no available API to query those. Thus unable to gather precise location information.

Yes that's why i thought about this workaround for some time now 😀

> The idea sounds great, its a really interesting challenge to tackle, most of the time can't just use the straight path to gather the node, but have to actually take a path to get there. In my observation, some of the gatherable nodes placed in a really tricky location. Just recalling few locations at [Un'Goro Crater](https://classic.wowhead.com/ungoro-crater) 😓

Yes absolutely, it is kind of a challenge 😀 For the nodes it can't reach there has to be some kind of detection.. like if it found a node and it doesn't reach it within x seconds it should blacklist this node for x minutes or even the whole session. Also sometimes there are "underground" nodes, that are colored in a dim yellow on the minimap.

**Comment by Xian55** [comment]
Started working on it today, it's a bit rough, but at least the original `AttendedGather` is working, and a bit more efficient in terms of resource management. Properly stopping and resuming.

Also as you noticed the player won't attempt to defend itself upon entering combat. This was actually intended in the past, however can easily implement the combat handling.

The next Pull request going to contain the approach target - combat - loot - skin - buffing - repair and selling modules, when using `AttendedGather` mode.

The suggested semi automated node pickup with approach pathing wont be available when i close #276 issue.

**Comment by horstc** [comment]
Thanks for your efforts, sounds great! 🙂 Didn't actually know, that combat handling was not part of the original mode. But in my opinion this would absoulety make sense...

While farming nodes (manually) I found another thing, that an automated gather feature would need. Sometimes there are areas with nodes that you don't want to pickup. So it would make sense if the gather profiles would have kind of a whitelist or blacklist. I saw the name of the node is showing on mouseover in the minimap, so if the bot find's a new yellow dot on the minimap, it could check if it is a valid node by using the addon.

This would be possible by using the MINIMAP_PING event and this line:

`local line = _G['GameTooltipTextLeft'..1]:GetText()`

So if it finds a node (yellow dot), it just has to click on it one time to transfer it's name. 🙂

Just some thoughts 😀

**Comment by Xian55** [comment]
Getting the yellow node name worth to be tracking, good idea. 

However i'm not a big fan of having a whitelist/blacklist in other words have the ability to skip the nodes. 

The reason is, if you having a fixed route what you keep scanning, and not picking up every node you gonna reach a point when there will be no new nodes added to the spawned pool, so you likely going to run around and not picking up anything.
