### ISSUE TITLE
AttendedGather: not using mount when UseMount = True

### ISSUE THREAD

**Issue by illidus** [Xian55/WowClassicGrindBot#281]
### Description

When running "AttendedGather" mode, I expect that when UseMount is enabled, that the mount would be used to move between gather nodes.

However, the player never mounts and ends up walking the entire time.

Seems like I am experiencing a similar issue that was mentioned in another recent issues comment section.

### Addon Version

1.2.5

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

1. Using Dev build from April 27, 2022
2. Start Ppather
3. Start BlazorServer
4. Run Init with a homogenous sky with bags open
5. Start class json, I have used an editted version of Paladin66 json with attendedgather added referencing "_herb\\12_Elwynn Forest_herb_optimal.json" path with UseMount = true.
6. Start bot

### Screenshots

![image](https://user-images.githubusercontent.com/2293976/165815951-cdddc01c-e309-4241-afdc-fbf49217d3ec.png)

### Logs

[out20220428_004.log](https://github.com/Xian55/WowClassicGrindBot/files/8585192/out20220428_004.log)

**Comment by Xian55** [comment]
Can you upload the class config profile what are you using?
Im referring to `Paladin_herb.json`

**Comment by illidus** [comment]
Certainly.
[Paladin_herb.txt](https://github.com/Xian55/WowClassicGrindBot/files/8585284/Paladin_herb.txt)

It wouldn't let me upload the json so changed to txt.

Thanks

**Comment by Xian55** [comment]
So just for clarification. The MountKey has been assigned to `N1` which means `Numpad 1` hotkey. Since the attended gatherer improvements. The `MountHandler` going to check the `N1` keybind in game, such as the actionbarkey is `Usable` and `Has no Cooldown or GCD`.

Here's the keymapping what the bot uses baked in. Also an example where i assigned the mount to `N8`.

![image](https://user-images.githubusercontent.com/367101/165821786-56b6aab7-50ec-450c-9000-e2f2cb8efe2c.png)

Upon looking at your actionbar i can see nothing is assigned to `N1`.

Other words, if you want to solve your issue you have to assign the mount item at your actionbar to the
`BottomRight Action Button 1` = `N1 or Numpad 1`

I hope this explanation helps.

**Comment by illidus** [comment]
Thanks for the response. I have actually bound Numpad1 to my action bar, it is the furthest left button on the top most bar. The UI only shows "Nu..". I have been able to use the numpad 1 and the mount action works.

**Comment by Xian55** [comment]
Yes your certainly did bound `Numpad1`. However to the opposite actionbar. Exchanged BottomLeft with BottomRight actionbar.

**Comment by illidus** [comment]
Sorry, I understand now. It is working. Thanks for your help!
