### ISSUE TITLE
[WIP] Better support for Retail client

### ISSUE THREAD

**Issue by alex498** [Xian55/WowClassicGrindBot#327]
### Description

In the retail we have only main path for finding and killing mobs
Also to work in new location we need to tweak addon to prevent giving mapId that bot doesn't know

### Addon Version

1.1.42

### World of Warcraft Client

Retail

### Reproduction Steps

1. Go to retail
2. Die from any mob
3. Stuck cause we have no pathfinder there

**Comment by Xian55** [comment]
Hello there! Thanks for reaching out for support.

First and foremost, with the currently compiled [JSON dataset](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Json/dbc) only gives support up to `The Burning Crusade` content both in `Classic` and `Retail` version of the game client. Personally my next goal is to fully support `Wrath of the Lich King Classic` when it airs.

In order to give better support for `Retail` version of the game there are some things to be done, most likely there are more things what came to my mind in this instant:

### Addon

Fix lua errors. The classic version of the addon might uses APIs which are deprecated in Retail.

Update the Icon **id**s to detect spells for buffs, debuffs and range. [Storage.lua](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Addons/DataToColor/Storage.lua)

### Json dataset

Running the respected [Utilities](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Utilities) projects while changing the data source.
* [ReadDBC_CSV](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Utilities/ReadDBC_CSV)
* [NPCs](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Utilities/ReadItems)
* Have to find a Retail NPC data set which contains at least npc names and IDs.
* [WowheadDB_Extractor](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Utilities/WowheadDB_Extractor)

### Pathfinder

V1 Pathfinder not going to work, since in Retail `MPQ` files no longer exists. I haven't really looked into the `CASC` file system.

V3 Remote pathfinder could be possible 
* Compile [TrinityCore](https://github.com/TrinityCore/TrinityCore) master branch
* Have to modify the [slope config in MapBuilder.cpp](https://github.com/TrinityCore/TrinityCore/blob/master/src/tools/mmaps_generator/MapBuilder.cpp) in order to accommodate the mesh for player movement.
* Extract  the maps-vmap and finally the mmaps
* Update the [AmeisenNavigation](https://github.com/Xian55/AmeisenNavigation/tree/feature/guess-z-coord-after-rewrite) branch to accommodate the magic file changes.

**Comment by alex498** [comment]
May I write to you in discord or somewhere else?
I have some other ideas about evolution of your program

**Comment by Xian55** [comment]
hi

**Comment by Xian55** [comment]
Since #383, Retail dataset not yet added to the project. Retail support is halted, until further consideration.
