### ISSUE TITLE
Blacklist spots, vendoring.

### ISSUE THREAD

**Issue by KayleMine** [Xian55/WowClassicGrindBot#432]
# Most important
- Blacklist spot's, like draw an sphere or box at some coord's to avoid that painted "zone".
Also mb auto-blacklist stuck zone's to prevent stuck in feature.
It's needed to prevent situations like that:
P.s bot can't get out from spot on screenshot, also it's not even possible with hand's too.
<p align="center">
   <img width="600" height="300" src="https://i.imgur.com/bQqnPo2.png">
 
 </p>

# Semi important
- Pause any other routine while go to vendor, so when bot follow vendor path and meet npc that attacks him, he ignore that and keep run to vendor.
Currently:  He dismout and fight, btw meanwhile char is fully broken, so just r.i.p
 (idk is that bug on my side or it's not implented on bot side, or i did not read something in api btw)

# Would be nice, but not critical.
- Path Editor/Recorder and feature to make  fly path.
P.s Why it not records Z coord? Or there is other way?

**Comment by Xian55** [comment]
Hello there. 👋 

I see some great ideas here. Currently don't have the spare time to work on new features, only fixing critical issues and bugs.

---

> Blacklist spot's, like draw an sphere 

Should be doable yes, requires some route file parsing rework to make it possible.

About the provided image, i'm not even sure you can leave that spot even with jumping, seems like a really extreme situation.

--- 

> Pause any other routine while go to vendor, so when bot follow vendor path and meet npc that attacks him, he ignore that and keep run to vendor.

It is possible to soften the requirement with the `InCombat` flag when to [engage upon entering combat](https://github.com/Xian55/WowClassicGrindBot/blob/38a0e65a627fbe341f50f2824378130d829d21ce/Core/Goals/AdhocNPCGoal.cs#L93)


--- 

> Currently: He dismout and fight, btw meanwhile char is fully broken, so just r.i.p

Not so long ago added a [new](https://github.com/Xian55/WowClassicGrindBot/pull/387) value to compare `Durability%`, can use that over awaiting for fully broken gear. Many class profiles requires some tidy up in order to bring them up to date.

---

> Path Editor/Recorder and feature to make fly path.
> P.s Why it not records Z coord? Or there is other way?

To my knowledge there's no public addon api which exposes the player Z coordinate. Only be able to extract the player map coordinates (x,y) with 0-100 percentage. Based on that can make a terrain sampling to determine the Z coordinate thus converting the local map coordinate to world coordinate system. However sampling method doesn't work with flying as it relies on the terrain for the height.

This has been a limitation of the nature of pixel based project, and reached the current capabilities.

**Comment by Xian55** [comment]
> Pause any other routine while go to vendor, so when bot follow vendor path and meet npc that attacks him, he ignore that and keep run to vendor.
Currently: He dismout and fight, btw meanwhile char is fully broken, so just r.i.p
(idk is that bug on my side or it's not implented on bot side, or i did not read something in api btw)

After https://github.com/Xian55/WowClassicGrindBot/pull/447 should less likely to die due broken equipment's.
