### ISSUE TITLE
No Line of Sight Handler

### ISSUE THREAD

**Issue by LaneBren** [Xian55/WowClassicGrindBot#433]
**Is your feature request related to a problem? Please describe.**
No way to handle being out of line of sight with target.

**Describe the solution you'd like**
Add a property that indicates when target is not in line of sight so users can add their own sequence in class config.

**Describe alternatives you've considered**
Could modify pull sequence of pet classes to attack first and have mob run to character for more reliable combat. Put pet on defensive so it only attacks after character is attacked and ensures mob in line of sight.

**Additional context**
Any pet class that is brought into combat by their pet can be out of line of sight of character. Character then tries to use abilities and looks very obvious to other players. Adding the line of sight property could let players run Approach sequence instead.

**Comment by Xian55** [comment]
Currently the line of sight error is not being detected by the addon as an issue, nor the backend has any knowledge about how to handle it.

> Add a property that indicates when target is not in line of sight so users can add their own sequence in class config.

I'm not entirely sure how to handle line of sight as multiple situation come to my mind as of this moment:

* pulling a melee mob: this should be no problem, as the AI primary goal is to get in melee range to the player as soon as possible.
* pulling a caster mob: without interrupting the enemy castbar, it prefers to stay in place and blast from its combat start location. Calling back the pet is an option here which is bound to the **StopAttack** KeyAction.

I can make it possible to disable the automatic pet attack from c# code, and move it to the ClassConfig, to be able to configure pet control more. 

However, based on your other post i saw you are playing Death Knight, unless you are Unholy with the given talent which gives the ability to fully control the pet, the default ghoul has a really bad AI behavior where it attacks everything, since in the backend its a totem you have no control over it.

> Could modify pull sequence of pet classes to attack first and have mob run to character for more reliable combat. Put pet on defensive so it only attacks after character is attacked and ensures mob in line of sight.

Certain classes, like hunter is unable to use bow in melee range thus doing less damage. Warlock, mage seems to be unaffected. For melee classes yes its a preferred way to get in melee range as soon as possible.

The main idea was that, some classes are pretty weak, like warlock early level, so the pet should engage first to build up some threat, so the player can blast right from the start, without losing too much health.

**Comment by Xian55** [comment]
Hey just pushed two changes recently:
* https://github.com/Xian55/WowClassicGrindBot/pull/434
* https://github.com/Xian55/WowClassicGrindBot/pull/435

If you have time, i would appreciate if you could check out and give some feedback about the changes. Really important that, the changes only available from addon version `1.7.21`

* Pull down the repo with this commit included https://github.com/Xian55/WowClassicGrindBot/commit/b1ec23e92004de334c6cde8e55be8a9c7a1eb2cc
* Rebuild
* Should see `New Addon version available!` at the Blazor front page -> `Update` -> `Install`
* Complete the [Frame Configuration process](https://github.com/Xian55/WowClassicGrindBot#5-blazorserver-configuration-process)
* Then ready to go

**Comment by LaneBren** [comment]
Awesome, thanks for this. I will test as soon as I can.

> However, based on your other post i saw you are playing Death Knight, unless you are Unholy with the given talent which gives the ability to fully control the pet, the default ghoul has a really bad AI behavior where it attacks everything, since in the backend its a totem you have no control over it.
> The main idea was that, some classes are pretty weak, like warlock early level, so the pet should engage first to build up some threat, so the player can blast right from the start, without losing too much health.

This is for a 80 Hunter config I am tweaking now, but probably more useful for lower level pet classes as you state.

> Certain classes, like hunter is unable to use bow in melee range thus doing less damage. Warlock, mage seems to be unaffected. For melee classes yes its a preferred way to get in melee range as soon as possible.

With !TargetsMe and AfterCastStepBack, you can get into ranged reliably after the pull and aggro swap. But it slows things down significantly, so not ideal.

**Comment by LaneBren** [comment]
[out20221009.log](https://github.com/Xian55/WowClassicGrindBot/files/9741799/out20221009.log)

Log with the errors, first pull with AutoPetAttack enabled and second without. It is calling out the error now, but doesn't know what to do it seems? It is dropping target only when the pull takes too long.

**Comment by Xian55** [comment]
Hey the error what you are referring to with the `Hunter mark` is an another issue. In order to investigate further, i need the `_Hunter_80_farm_pet_pull.json` file.

From Addon version `1.7.22` Hunters mark should work properly after https://github.com/Xian55/WowClassicGrindBot/pull/439 be sure to check out the [example profile](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Json/class/Hunter_70.json) about it.

**Comment by Xian55** [comment]
Did you had time to try out the new features, regarding the hunter's mark ?

**Comment by LaneBren** [comment]
I just modified file with your cast sequence here:

[_Hunter_80_farm_pet_pull.txt](https://github.com/Xian55/WowClassicGrindBot/files/9805214/_Hunter_80_farm_pet_pull.txt)


I copied your pull sequence with the hunter's mark, but doesnt seem to handle the line of sight issue. It is more of a in-combat issue than during the pull sequence, because the pet still attacks.

[out20221017.log](https://github.com/Xian55/WowClassicGrindBot/files/9805213/out20221017.log)

Also, since you are adding hunter buffs/debuffs - aspect of the dragonhawk needs to be added

**Comment by Xian55** [comment]
Added a few more buffs and debuffs. https://github.com/Xian55/WowClassicGrindBot/pull/445

**Comment by Xian55** [comment]
Line of sight detection should properly working since https://github.com/Xian55/WowClassicGrindBot/pull/446
