### ISSUE TITLE
remote access to localhost:5000 not working

### ISSUE THREAD

**Issue by Phatlynx** [Xian55/WowClassicGrindBot#436]
### Description

Hello, I followed the steps in the read.me on opening port 5000 and tried to connect to localhost:5000 from my phone within the same wireless network and it says the site cannot be reached. 

### Addon Version

Current version

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

1. Followed steps for opening port 5000 in windows defender
2. Tried to access http://localhost:5000 from my phone
3. This site can’t be reached
localhost is currently unreachable.
ERR_CONNECTION_FAILED

### Last Good Version

N/A

**Comment by Xian55** [comment]
Hello there 👋 

The `localhost` address resolved to `127.0.0.1` IPv4 address. Which means these two addresses only accessible on your local machine, in your context is your **phone**.

I assume you are not running any service on your phone which occupies the `5000` port so the `ERR_CONNECTION_FAILED` error message is valid.

---

In order to access the `BlazorServer` from your phone, first you have to find out your host local ip address.
Press windows key > start type `cmd` > enter > open cmd > type `ipconfig` > enter.

You supposed to see the something like this, where there could be multiple adapters.

![image](https://user-images.githubusercontent.com/367101/194706146-6bbe8cdf-ed02-4a83-8f47-5287d83ea2a5.png)

Switch to you phone, open the wifi options and find the connected network details, look for the default `Default Gateway` address. 

Once you found a matching Default Gateway address, on your PC, pick the IPv4 Address, and you have to replace with the `localhost` => that address.

Based on the provided example, in your phone browser you should type http://192.168.0.10:5000/

**Comment by Phatlynx** [comment]
Issue resolved. Thank you.
