### ISSUE TITLE
when back home to repair ,keep dead

### ISSUE THREAD

**Issue by jsRuner** [Xian55/WowClassicGrindBot#444]
### Description

Because the weapon is broken, you can't hit the monster. Whether the weapon durability value can be configured and trigger conditions

### Addon Version

latest

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

no step

### Last Good Version

latest

### Logs

no logs

**Comment by jsRuner** [comment]
It can't be repaired when the weapon is damaged, which causes death all the time

**Comment by jsRuner** [comment]
You will enter the battle on the way back to maintenance

**Comment by Xian55** [comment]
Hello there 👋 

You have a good point here, however others already suggested to make improvement regarding this topic.

I'm aware that all profiles are using `Items Broken`.

Since https://github.com/Xian55/WowClassicGrindBot/pull/387 you have the option use `Durability%` over `Items Broken`.
This construct allows more granular tuning over a hard value.

example:

```json
"NPC": {
    "Sequence": [
    {
        "Name": "Repair",
        "Key": "C",
        "Requirement": "Durability% < 40",
        "PathFilename": "Tanaris_GadgetzanKrinkleGoodsteel.json",
        "Cost": 6
    },
}
```

**Comment by jsRuner** [comment]
thanks ,i no see it.  thinks again

**Comment by jsRuner** [comment]
i close it
