### ISSUE TITLE
AmeisenNavigation Help

### ISSUE THREAD

**Issue by rozv11e** [Xian55/WowClassicGrindBot#449]
### Description

Hi, I can’t build the AmeisenNavigation project because the AnTCP.Client.1.0.0.nupkg package is missing, and when compiling it gives an error of the second package - newtonsoft (can’t find version 13.0.1) help me solve the problem, I want to try using v3 paths in dungeons

Will this navigation work in dungeons?

### Addon Version

0.0.0

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

1. download  VS
2. Can build AmeisenNavigation
3. nuget packages

**Comment by Xian55** [comment]
Hello there,

AmeisenNavigation requires Visual Studio 2019 to be installed. Also be sure to the `Desktop Development with C++` module is installed as well.

Once you have that be sure to set `AmeisenNavigation.Server` as startup project.
And unload project `AmeisenNavigation.Tester` as that one dosen't needed.

With these settings should be able to compile the `AmeisenNavigation.Server` project.

---

However the provided [mmaps files](https://github.com/Xian55/WowClassicGrindBot#22-using-v3-remote-pathing) doesn't contain any instance/raid navigation meshes. As the related in game addon api returns (0,0) coordinates inside dungeons and raids. So you have to find an another way to supply player position info from the game.

**Comment by rozv11e** [comment]
Thanks, installed.
the only option is to find the mmaps file with the paths for the dungeons? There are no other options?
Some lk dungeons can be farmed in 1 player, this will also help to avoid a possible ban, and increase the farm

**Comment by Xian55** [comment]
This has been asked before, https://github.com/Xian55/WowClassicGrindBot/issues/344

There are other options, yes, but it requires to hook into the executable and read the game memory to obtain the player location, which goes against the project principle. You can make modification on your own, but use it on your own risk.

---

You can extract the `mmaps` on your own, it takes a little bit of time, here's a little guide about that.

**1. Requirements:**
- [TrinityCoreTools.zip](https://github.com/Xian55/WowClassicGrindBot/files/9940912/TrinityCoreTools.zip) (On the other hand you can compile it on your own)
- WoW 3.3.5a Client

**2. Move the Tools to your WoW folder**
![unknown](https://user-images.githubusercontent.com/367101/200042667-6e6f07f5-335d-47b3-8f07-81eda2460567.png)

**3. Run the Tools**
Things you only need to do once:
```
mapextractor.exe
```
```
vmap4extractor.exe -l
```
```
vmap4assembler.exe Buildings vmaps
```

Run this to generate the MMAPs (note this takes ~20min on a Ryzen 7 3700X) and make sure to set a good maxAngle (I use 50).
```
mmaps_generator.exe --maxAngle 50
```

**Comment by rozv11e** [comment]
Are there any other options without reading the memory to use the bot in the dungeon?

**Comment by Xian55** [comment]
I have yet to find an alternative way. 

To my best knowledge the only reliable way to have a navigation system, is memory reading.

**Comment by rozv11e** [comment]
And why can't the bot itself extract resources (grass, ore)?

**Comment by Xian55** [comment]
Personally i had no intention to use it as gathering herbs and mines.

With the current setup, the navigation system is not that precise, to make consideration about tight corners, and extreme slope angles and not using click to move, but rather simulating WASD keystrokes. As a result the movement is a bit random and imprecise this effect has advantage and disadvantage. 

* For generally running around and pulling mobs works quite well.
* For collecting herbs and veins not really, as some of the nodes are placed a really tricky location.

On top of this, the `WowClassicGrindBot` backend has no notion of the nodes on screen, it can only rely on the minimap yellow icon for direction. 

It is not impossible to make it function, but requires lot of effort to make it work properly. I myself yet to find ambition to spend  time working on it.

Among us, [coolzoom](https://github.com/coolzoom/WowClassicGrindBot/tree/herbtest) who spent some time working on it, but after time he has deemed the solution not yet ready make it work reliably, mostly because of the previously mentioned challenges.

If you have the spare time to working on it, i encourage you to do so. 🙇

**Comment by rozv11e** [comment]
I may have an idea how to avoid the ban to some extent by using different paths.  for example: he follows one path for 4 hours, sells, and then follows another path, in fact, just rearranging the paths, and so on, it would also be useful to add a mail function so that after selling the trash, he can transfer the necessary items to the twink

**Comment by Xian55** [comment]
> I may have an idea how to avoid the ban to some extent by using different paths. for example: he follows one path for 4 hours, sells, and then follows another path, in fact, just rearranging the paths, and so on,

Somebody else suggested it in prior. It would be a really good addition to the project indeed. Having the option to alternate routes.

Keep in mind, not recommended to use it for a long period of time. Have to find a good balance.

> it would also be useful to add a mail function so that after selling the trash, he can transfer the necessary items to the twink

Mailing options would be nice. Have to do some research what capabilities the in-game lua API exposes.

---

Keep the conversation related to the original post. You have the option to [request new feature](https://github.com/Xian55/WowClassicGrindBot/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=) or [report bug](https://github.com/Xian55/WowClassicGrindBot/issues/new?assignees=&labels=bug&template=bug_report.yml).

**Comment by Sattva-108** [comment]
> AmeisenNavigation requires Visual Studio 2019 to be installed. Also be sure to the `Desktop Development with C++` module is installed as well.

Do you mean **Microsoft Visual Studio Professional 2019** has to be installed?

**Comment by Xian55** [comment]
Hey in the past needed at least
* Visual Studio Community 2019 
* ![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/521b12b5-e207-4e79-b5ca-37ede6668845)

installed in order to build build the AmeisenNavigation project.

However that's the old case. For the current flow, please follow #585.
