### ISSUE TITLE
Ability to work with 1 profile for class (and or path?)

### ISSUE THREAD

**Issue by Darkjamin** [Xian55/WowClassicGrindBot#459]
Hi,

I've read the documentation and tried to find how this is implemented, but I couldn't.
Is there a way to kind of have the bot change paths depending on it's level.

I explain: 
Currently I go in the class file and set up the path I want the bot to grind. While at higher levels this is ok, as it would take some time for the bot to level, at low level, it's kind of harbour intensive.

Is there a way to say, in a class file for example, or 1 big 1-60 file:

If char 1-3 : "PathFilename": "xxx.json"
If char 4-5: "PathFilename": "yyw.json"
...

Or maybe in the path profiles? Maybe this function already exist and I did not see/understand how to use it?

Thanks.

**Comment by Xian55** [comment]
👋 Good day!

> Is there a way to kind of have the bot change paths depending on it's level.

There's no such functionality. During runtime, the framework does not support changing the route on the fly.

---

For Vanilla and TBC:
Generally speaking, below level ~35, every second or forth level, new signature ability getting introduced to nearly every class. Prioritizing abilities and cooldowns can be picked by personal choice, not to mention talent choices, to create these complex class rotation profiles requires lot of testing, it is mostly trial and error from my part. Could take considerable time.

In order to tackle such task, what you looking for, first have to separate `Route` related settings from the `ClassConfiguration` such request already present(#432).

As of the near future, i have no plan to work on such feature/rework.

🙇

**Comment by coolzoom** [comment]
> For Vanilla and TBC: Generally speaking, bellow level ~35, every second or forth level, new signature ability getting introduced to nearly every class. Prioritizing abilities and cooldowns can be picked by personal choice, not to mention talent choices, to create these complex class rotation profiles requires lot of testing, it is mostly trial and error from my part. Could take considerable time.

Agreed, it requires too much work. Even fully unlocked Lua required few mega lines of code just for a single class.(eg https://github.com/cxmplex/ProjectSquidFireMage)
We should focus on learning, optimizing, and structure-based changes here. so someone who has interests on it can use this as the starting point to go further.

**Comment by Darkjamin** [comment]
Thank you for your responses. I can see your point and agree.
