### ISSUE TITLE
Healer Class Setup

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#522]
**Is your feature request related to a problem? Please describe.**
I would like to build a profile around leveling with a pocket healer

**Describe the solution you'd like**
Be able to heal/buff  focus target

**Describe alternatives you've considered**
I am not sure of any class commands to heal the focus target or a specific named player

**Additional context**

**Comment by Xian55** [comment]
Hi, as of now, currently about the `focus` target, only a very limited info getting extracted by the addon. Mostly about the `focus` and `focustarget` exists and if any of them affected by combat or the `focustarget` is hostile.

From both the addon and the backend side have add some new cells to cover `Health` and `MaxHealth` in order to calculate `Health%`. On the other hand needs a queue for getting the `focus` buffs to get timers. All of this shouldn't be a problem.

The tricky part is to somehow find a way in the during combat, from the pocket healer side to be able to switch target depending on what action it supposed to do. Example when there's no *danger* defined by the class profile, the healer should do some damage, otherwise have to buff the protected player.

Probably the easiest way would be is to create a new `CombatGoal` like behaviour, example. `AssistFocusGoal` which has a higher priority by default, and it automatically targets the protected one.

**Comment by adamssullivan** [comment]
Thanks again for getting back so fast. Do you have an example of the AssistFocusGoal? I am not seeing it in the documentation.

**Comment by Xian55** [comment]
That goal does not exists yet.

Im working on it. The backend requires some work in order to accomodate the focus target. However luckily the existing buff structure and logic can be reused.

So, what is currently working for the player buffwise should work for the focus target as well

**Comment by adamssullivan** [comment]
Oh, Fun! I am able to use some heals in ad-hoc because of TargetHealth. Thanks again.

**Comment by Xian55** [comment]
Hey, just merged #523 where thee addon version has been increased to `1.7.44`.

Updated the docs file as well with [Assist Focus Goal](https://github.com/Xian55/WowClassicGrindBot#assist-focus-goal) section. Be sure to read it first and try to digest it.

I've added an [example druid](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Json/class/Druid_80_moonkin_assist.json) profile with mainly moonkin in combat.

The profile has some basic things in it like
* If the `focus` is mounted, then the player mounts as well
* `Adhoc` section Buffs the player it self just like before
* `AssistFocus` section throws buffs and heals on the `focus`/`party1` unit

Other then that feel free to ask if you are feeling blocked in any way or if i left something out.
