### ISSUE TITLE
[Question] Documentation KeyAction / Pathfinder differences

### ISSUE THREAD

**Issue by tidusete** [Xian55/WowClassicGrindBot#530]
### Description

Question about documentation:
I have set up all the environment and the program is working fine but sometimes my character does not target anything or do some weird stuff although is being attacked. In order to solve it by myself, I'm reading all the documentation.

Since I only tested like 4h I would like to ask some questions about the documentation:
**Keybindings:**
https://github.com/Xian55/WowClassicGrindBot/blob/dev/README.md?plain=1#L307C1-L307C66
We assume that  `"I"` will be InteractKey but why we also define | `"HearthstoneKey"` | `Consolekey` to be pressed to use hearthstone | true | `"I"` |

It will override it? what does Consolekey mean?

### Addon Version

1.7.0

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

documentation

**Comment by Xian55** [comment]
👋 Hello there

Thanks for reaching out for help. 

> program is working fine but sometimes my character does not target anything or do some weird stuff although is being attacked

To start an investigation about your issue please provide `*.log` files. You can find it next to the executable. 

example file format: `out20221004.log`

- `WowClassicGrindBot\BlazorServer_or_HeadlessServer\`
- `WowClassicGrindBot\BlazorServer_or_HeadlessServer\bin\Release_or_Debug\net7.0`
- `WowClassicGrindBot\BlazorServer_or_HeadlessServer\bin\x64\Release_or_Debug\net7.0`
- `WowClassicGrindBot\BlazorServer_or_HeadlessServer\bin\x86\Release_or_Debug\net7.0`

On the other hand, it would be nice if you could explain about what happens during these "weird stuff". If you could give a description about, what happens around the player character and what the character is doing, it would be really helpful for a start.

---

> We assume that "I" will be InteractKey but why we also define | "HearthstoneKey" | Consolekey to be pressed to use hearthstone | true | "I" |
>
> It will override it? 

It might seen as a conflict, your assumption is correct. However the `HearthstoneKey` **not in use**. In the past before i forked the repo it may have been used by the original author, you can say its unmaintained code now days. Since then it not used by the `Core` code or any of the `GoapGoal` as of today.

> what does Consolekey mean?

Its [enum](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum) where all the possible valid keyboard keys are defined. You can look at the [official docs](https://learn.microsoft.com/en-us/dotnet/api/system.consolekey?view=net-7.0)

I'm going to update the docs in this regard to avoid confusion.

**Comment by tidusete** [comment]
Hey @Xian55 yesterday I was playing a little bit more and started to check the logs. I have more questions as well.
Could you provide more documentation about the Pathing? (Using V1 Local/Remote Pathhing / Using V3 Remote Pathing)  What and which are the differences? Or if you can provide me more documentation I will glad to help you. 
This link does not work anymore: https://ameisenbotx.de/Thread-How-to-run-the-server (at least you can reach it form waybackmachine)

I'm starting to think that my problems are there. If I open the Blazor server at the beginning I tries to use the V1 Local but after a while I start the Remote Pathing server to test and play a little bit on it in order to understand what i does and I receive weird logs from the Remote Pathing server (Like out of the array).

My end goal  is to be able to farm some instances and I believe in order to achieve it I just need to understand the Pathing feature.

**Comment by Xian55** [comment]
> Could you provide more documentation about the Pathing? (Using V1 Local/Remote Pathhing / Using V3 Remote Pathing) What and which are the differences?

Definitely, i can improve on this section of the docs. Later on im going to try to explain in better structure.

Early on, i was experimenting with the pathfinding. V1 was in a really bad shape when i started using the repo. However after time i've managed to improve on the speed and memory allocations aspects. So as of today, i would say you wouldn't notice the time difference on V1 and V3 while using the bot. Personally i would prefer V1.

For now, in short V1 uses MPQ files as source, while V3 uses prebaked navmesh from TrinityCore private server. V1 extracts the geometry on the fly and caches the calculated paths thus its slower but from my experience it works better for most scenarios than V3. V3 is super fast, that's the only benefit really.

> My end goal is to be able to farm some instances and I believe in order to achieve it I just need to understand the Pathing feature.

From the Readme, it's been stated that dungeons and instances are not supported by the none of the Pathfinders.

**Comment by Xian55** [comment]
Hey, readme updated with [technical details](https://github.com/Xian55/WowClassicGrindBot#21-using-v1-localremote-pathhing) for V1 and V3.

**Comment by tidusete** [comment]
Cool thanks! I will try to work/play a little bit on it
