### ISSUE TITLE
Thinking about the name of the service, and Blizzard's surveillance of background processes

### ISSUE THREAD

**Issue by Shoomie** [Xian55/WowClassicGrindBot#532]
Just a quick idea:
Since it's pretty much established that blizzard does conduct surveillance of running processes through the battle.net launcher, it might be wise to at least not name the program something with "bot" in the name, or perhaps include a function which easily lets the user set the name of the process himself at execution.

**Comment by Xian55** [comment]
Hello 👋 

First thing first, the repo it self does not take the responsibility to make public releases of the applications(BlazorServer, HeadlessServer, PathingAPI)

However since you have access to the source code you have the option to use [dotnet publish](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish) command. Here, you can adjust many info about the executable info, such as visible name, version number, you can even sign your application.

Create a [PublishProfile](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#pubxml-files) to quickly reuse / redeploy the app(s).
In Visual Studio, there's a really user friendly GUI, which allows to alter most of the parameters.

Also you can opt-in to disguise the application(s) as one of the most popular app such as browsers(chrome, firefox, etc...)

---

In case you concerned about `Battle.net` services, be sure don't let them run as Administrator privileges - beside the Updater Agent - and after starting the game, exit Battle.net. Then make sure the `Battle.net Agent` does not run in the background.
