### ISSUE TITLE
merging gathering and grinding

### ISSUE THREAD

**Issue by Lonewolfofazeroth** [Xian55/WowClassicGrindBot#557]
can u suggest some clue to how merge gathering and grinding system
thanx alot

**Comment by Xian55** [comment]
Gooday!

Fully automated gathering is not supported in the project.

Currently [AttendedGather](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#modes) mode is available, which it requires user input to collect each node.

Since Dragonflight the `InteractKey` now has the [capability](https://github.com/Xian55/WowClassicGrindBot/issues/531#issuecomment-1688634434) to consider GameObject as well. Such as mailbox, mining veins and herbs, etc.. So the previously mentioned part of manual user input, can be improved, just have to find a way to detect the in game state when a GameObject soft target is present.

Nonetheless, the Navigation still not that precise to handle outdoor movement with really tricky placed mining nodes, which sometimes give headache to reach.

On the other hand navigation inside buildings and caves can be problematic, not that reliable and requires some pre conditions to make it work. Last year summer, i've spent a great deal amount of time improving the reliability and effectiveness of the default pathing solution, it still requires some attention.

If you wish to spare some time to figure out how the system already composed, i could suggest a few classes what you can take a look:
* [ClassConfiguration](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/ClassConfig/ClassConfiguration.cs) Has the [Mode](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/ClassConfig/ClassConfiguration.cs#L19) which determines what logic to execute, you can find more detail on the [readme](https://github.com/Xian55/WowClassicGrindBot/blob/dev/README.md)
* [FollowRouteGoal](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/Goals/FollowRouteGoal.cs) as the name says, follows the given route and meanwhile does minor task(**sideActivity**) either **Thread_LookingForTarget** OR **Thread_AttendedGather**, finds yellow nodes on the minimap.
* [Navigation](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Core/GoalsComponent/Navigation.cs) this goal Component is responsible to handle the route navigation requests and do the pathfinding if necessary.
