### ISSUE TITLE
Inventory Management issues (white items)

### ISSUE THREAD

**Issue by augerT** [Xian55/WowClassicGrindBot#558]
### Description

Playing SoD

Using the suggested sell macro I'm unable to sell any white items. My grey items vendor, repair works, but I cannot sell any specified white items.

my macro:

```
/tar Ott
/run DataToColor:sell({"Gooey Spider Leg", "Crisp Spider Meat"});
```

Does not sell either of the described items. I have this bound to "C" with bindpad

I also cannot seem to delete these items with the suggested macro

```
/run for b=0,4 do for s=1,GetContainerNumSlots(b) do local n=GetContainerItemLink(b,s) if n and (strfind(n,"Slimy") or strfind(n,"Red Wolf") or strfind(n,"Mystery") or strfind(n,"Spider L")) then PickupContainerItem(b,s) DeleteCursorItem() end end end
```

Thoughts / suggestions ? Really sucks to not be able to clean up garb in my inventory...

### Addon Version

1.7.50

### World of Warcraft Client

Season of Mastery

### Reproduction Steps

1. Setup suggested vendor / delete macro 
2. Try running macro
3. Macro does not rid inventory of described items

### Logs

[13:03:17:151 W] [AdhocNPCGoal   ] No target found by cursor(Vendor, Repair, Innkeeper)!
[13:03:17:151 I] [AdhocNPCGoal   ] Use KeyAction.Key macro to acquire target
[13:03:17:243 I] [AdhocNPCGoal   ] Found Target!
[13:03:18:182 W] [AdhocNPCGoal   ] Gossip no options! 877.0381ms
[13:03:18:182 I] [AdhocNPCGoal   ] Merchant window opened after 877.0381ms
[13:03:23:182 I] [AdhocNPCGoal   ] Merchant sell nothing! -5000.0933ms
[13:03:24:956 I] [NpcNameFinder] type = None | mode = Fuzzy

**Comment by Xian55** [comment]
Gooday,

Thanks for letting me know about the issue. I'm going to look into it, and see what's going on.

**Comment by augerT** [comment]
Thanks!

**Comment by Xian55** [comment]
Firstly, after doing a quick manual test,
* Go to a vendor
* Interact with it and be sure to open the merchant window
```lua
/run DataToColor:sell({"Refreshing Spring Water", "Crisp Spider Meat"});
```
works fine for me, the item is getting sold properly. So there must be other issue, with the timing. Proabaly executing the `sell` function to early when the merchant window is not yet open, I have to investigate more.

---

Secondly, the other macro doesn't work since blizzard had the wonderful idea to change old [existing api](https://www.reddit.com/r/woweconomy/comments/ye2ajy/vendor_sell_macro_no_longer_works/), move functions from global namespace under specific ones, so in order to make it work, you have to be more verbose in the macro, which going to limit what you can actually achieve.

So sadly that macro cannot fit in the 255 character limit.

**Comment by augerT** [comment]
Ahhh, "DataToColor" is the name of the addon, I had configured a different name on initial setup so that wasn't working. All good now!

Thank you for the quick help!

**Comment by Xian55** [comment]
Hey here's a working version of the item deletion macro, however it needs to include the namespace in order to call the Container related functions. So you have less items to include and still fit within the 255 characters

In the readme page, the example also updated, thanks for the notice.

```lua
/run c=C_Container for b=0,4 do for s=1,c.GetContainerNumSlots(b) do local n=c.GetContainerItemLink(b,s) if n and (strfind(n,"Slimy") or strfind(n,"Pelt") or strfind(n,"Mystery")) then c.PickupContainerItem(b,s) DeleteCursorItem() end end end
```

**Comment by augerT** [comment]
Hey thanks for this. It seems like there is still a timing issue when trying to sell with the bot. It sells greys but doesn't seem to run the macro and exits out of the merchant pretty quickly. Any way I could configure that to give it more time ?

**Comment by Xian55** [comment]
Gooday, i've made some adjustments both addon side and the backend side.
* In git, Be sure to pull the latest `dev` branch
* In git, be sure to resolve conflicts if you have any, to apply the changes.
* Start BlazorServer
* You should see `Update available` button. Press it, in order to update the addon.
* After it successfully copied the new version, you should see a loading screen, as the UI gets reloaded.
* If everything goes well, you supposed to see `Using 1.7.51` text in game.

After #562, the previously mentioned issue should be fixed, if you have time to checkout the change and give feedback, i would really appreciate your time. Let me know if you notice any problem regarding to this issue.

Have a nice day!

**Comment by augerT** [comment]
Hey! I'll give it a try when I get home today. Thanks again :)

**Comment by augerT** [comment]
Just tried it out and it seems to be fixed. Well done!
