### ISSUE TITLE
Feature Request - Ability to have multiple paths on a profile and to swap back and forth after a certain amount of time

### ISSUE THREAD

**Issue by adamssullivan** [Xian55/WowClassicGrindBot#577]
**Is your feature request related to a problem? Please describe.**
There is no problem. To seem more like a real player I would like to have the path change from between path profiles after a certain amount of time

**Describe the solution you'd like**
I would like to be able to add another path profile to the class profile

**Describe alternatives you've considered**
I don't think it is currently possible

**Additional context**

**Comment by Xian55** [comment]
Hello there,

That would be a good addition to the project. Separating the Class profiles from the route logic. In the past i did some work in that regard, when i was tinkering with the **Path Editor**(which allows to change the route and propagate the changes for every component which interested in the change). However more work needs to be done in order to be more suitable to fulfil the request.

I don't have a great deal amount of spare time to work on the project. Nor i was planned to tackle any kind of big features. Currently i have the project on life support, whenever a breaking change get introduced by the patches i planned to fixed them asap.

On the other hand, some time soon Cataclysm Classic is coming to Beta. Sadly the PathingV1 no longer going to work, due there are no MPQ files for that expansion. So probably only the PathingV3 remain to support the project. Which is fine.

I guess, there's going to be some kind of work needs to be done in order to support the upcoming classic expansion of the game. Maybe that time i could do some work unless somebody from the community steps up and do some additional work.

**Comment by adamssullivan** [comment]
Thanks for your reply. I have no coding experience or I would help.

**Comment by Xian55** [comment]
Since #582 this feature it's possible!

**Comment by adamssullivan** [comment]
Thanks. I will give that a try.

**Comment by Xian55** [comment]
There aren't many conditions to choose from as of now.

Also i have not found a clean way to express the following, for example:
* Please alternate the following 5 paths, spend 30 minutes on each then continue to the next. If it reached the 5th path resume from the first Path.
