### ISSUE TITLE
Could not find file 'D:\HuB\WowClassicGrindBot-dev\json\area\wrath\0.json'.

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#597]
Could not find file 'D:\HuB\WowClassicGrindBot-dev\json\area\wrath\0.json'.

how to solve this problem?

thanks!

**Comment by Xian55** [comment]
Hello!

That is correct, there should be no `0.json` named file in that folder as [Json/Area/Wrath/](https://github.com/Xian55/WowClassicGrindBot/tree/dev/Json/area/wrath) that file does not exists in the repository.

Most likely the cell cannot be read by the backend, that's why it is shows up as **0**.

Be sure to follow the [Configuration Process](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#5-blazorserver-configuration-process) carefully.

If the issue still persist, then you have to provide logs(next to the executable) and more info about your setup and what you are doing step by step, so then lets see if i can reproduce your issue.

Have a nice day!

**Comment by cppbeliever** [comment]
@Xian55  Thank you, bro。

**Comment by Xian55** [comment]
Closing, probably having a non properly configured `frame_config.json` which can be resolved by rerunning the [BlazorServer Configuration process](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#5-blazorserver-configuration-process)
