### ISSUE TITLE
Sometimes, characters cannot be resurrected.

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#602]
Sometimes, the character cannot be resurrected after death because the soul cannot go to the exact place of death. Is it because I have overlooked the setting? Or is there a bug in the current robot?

**Comment by Xian55** [comment]
Hello, without any logs, locations, context, i cannot tell what went wrong.

Please provide more details about your situations so we can start the investigation.

Have a nice day!

**Comment by cppbeliever** [comment]
> Hello, without any logs, locations, context, i cannot tell what went wrong.
> 
> Please provide more details about your situations so we can start the investigation.
> 
> Have a nice day!

I uploaded the video to youtube. The path of the character in the video was created by myself, overwriting Json\path\_pack\1-20\Dwarf.Gnome\10-12_Loch Modan.json

[https://www.youtube.com/watch?v=CU_NDS9FFNw&ab_channel=shixing](url)

**Comment by cppbeliever** [comment]
> Hello, without any logs, locations, context, i cannot tell what went wrong.
> 
> Please provide more details about your situations so we can start the investigation.
> 
> Have a nice day!

[00:49:07:343 I] [CombatGoal     ] Lost target!
[00:49:07:357 I] [GoapAgent      ] New Plan=  Walk To Corpse
[00:49:09:770 I] [WalkToCorpseGoal] Player teleported to the graveyard!
[00:49:09:770 I] [WalkToCorpseGoal] Corpse location is <26.5096, 57.203102, 0>
[00:49:09:827 I] [Navigation     ] Pathfinder - 245.12117 - <-5351.2285, -2881.58, 0> -> <-5539.7983, -2724.973, 0> 4.0667ms
[00:49:14:780 I] [WalkToCorpseGoal] Random jump
[00:49:25:291 I] [WalkToCorpseGoal] Random jump
[00:49:36:632 I] [WalkToCorpseGoal] Random jump
[00:49:48:152 I] [WalkToCorpseGoal] Random jump
[00:49:58:315 I] [WalkToCorpseGoal] Random jump
[00:50:09:196 I] [WalkToCorpseGoal] Random jump
[00:50:21:517 I] [WalkToCorpseGoal] Random jump
[00:50:32:471 I] [WalkToCorpseGoal] Random jump
[00:53:52:384 I] [WalkToCorpseGoal] Random jump
[00:54:03:216 I] [WalkToCorpseGoal] Random jump
[00:54:13:803 I] [WalkToCorpseGoal] Random jump
[00:54:23:883 W] [TargetBlacklist] (0,30416,)E) is player or pet!
[00:54:24:492 I] [WalkToCorpseGoal] Random jump
[00:54:59:251 I] [WalkToCorpseGoal] Random jump

**Comment by Xian55** [comment]
Please provide the Full log file, unredacted, no highlights.

Without full context i cannot help you.

**Comment by cppbeliever** [comment]
@Xian55 
HeadLessServer Log:[headless_out20240708.log](https://github.com/user-attachments/files/16122121/headless_out20240708.log)
BlazorServer log: [out20240708.log](https://github.com/user-attachments/files/16122139/out20240708.log)

The incident took place at 00:49:07

my json file:
[Mage_Gnome_10-12.json](https://github.com/user-attachments/files/16122162/Mage_Gnome_10-12.json)

my path file:
[10-12_Loch Modan.json](https://github.com/user-attachments/files/16122168/10-12_Loch.Modan.json)

**Comment by Xian55** [comment]
> HeadLessServer Log:[headless_out20240708.log](https://github.com/user-attachments/files/16122121/headless_out20240708.log) 

The file does exists, i'm getting 404 error.

>  BlazorServer log: [out20240708.log](https://github.com/user-attachments/files/16122139/out20240708.log)

This log file is partial, during midnight, a new file will be created(that's what you uploaded, so the **first** part is missing) also does not make sense to me.

Especially the part of `[GoapAgent      ] Inactive, kill credit detected!`, like as if you controlling the player character manually while the application running in the background.

The provided log does not describe the situation about the issue.

**Comment by cppbeliever** [comment]
> > HeadLessServer Log:[headless_out20240708.log](https://github.com/user-attachments/files/16122121/headless_out20240708.log)
> 
> The file does exists, i'm getting 404 error.
> 
> > BlazorServer log: [out20240708.log](https://github.com/user-attachments/files/16122139/out20240708.log)
> 
> This log file is partial, during midnight, a new file will be created(that's what you uploaded, so the **first** part is missing) also does not make sense to me.
> 
> Especially the part of `[GoapAgent ] Inactive, kill credit detected!`, like as if you controlling the player character manually while the application running in the background.
> 
> The provided log does not describe the situation about the issue.

This is the other part of the log you want
[out20240707.log](https://github.com/user-attachments/files/16124552/out20240707.log)
[out20240707_001.log](https://github.com/user-attachments/files/16124553/out20240707_001.log)
[out20240707_002.log](https://github.com/user-attachments/files/16124554/out20240707_002.log)
[out20240707_003.log](https://github.com/user-attachments/files/16124555/out20240707_003.log)

This is the HeadLessServer log I re-uploaded
[headless_out20240708.log](https://github.com/user-attachments/files/16124586/headless_out20240708.log)

**Comment by Xian55** [comment]
After looking at the provided [headless_out20240708.log](https://github.com/user-attachments/files/16124586/headless_out20240708.log) log file.

I can spot multiple issues. However the one which is related the navigation and pathfinding issue might be around using RemoteV3 pathfinder.

> [12:24:50:201 I] [Program        ] Using RemoteV3(RemotePathingAPIV3) 127.0.0.1:47111

May i ask which navmesh did you downloaded from [2.2 Optional - Using V3 Remote Pathing](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#22-optional---using-v3-remote-pathing) ?

Since you are using the

> [12:24:45:842 I] [Program        ] Version: 3.4.3.55417

You should be using the [Vanilla + TBC + Wrath](https://mega.nz/file/zWQ2XIKI#9EKWOPyyTMfY1LACkcP_wioZ0poVIuaGh2xcRh4V9dw), that's the pre Cataclysm zones.

Since you are using 

> [12:24:54:520 I] [BotController  ] ClassConfig: Mage_Gnome_10-12.json with Path: _pack\1-20\Dwarf.Gnome\10-12_Loch Modan.json

and based on the provided [video](https://www.youtube.com/watch?v=CU_NDS9FFNw) i can think of the following.

Loch Modan zone was significantly changed with the Cataclysm expansion to the point where using the new navmesh([Vanilla + TBC + Wrath + Cataclysm - work in progress](https://mega.nz/file/7Og32TDA#5HpxZ8Sh1XvDNCmWbI8H-cOFEJzDmh97Z6FGrO2p3X4)) may generate un reachable destinations.

---

Unrelated to the original issue, but it shows that the `CastingHandler` component does not work as intended.

> [12:24:54:884 I] [CastingHandler ] [Conjure Drink  ] castbar input 77ms -78.1474ms
> [12:24:54:910 I] [CastingHandler ] [Conjure Food   ] castbar input 77ms -140.4031ms
> [12:24:55:063 I] [CastingHandler ] [Conjure Food   ] castbar input 75ms -77.0971ms
> [12:24:55:094 I] [CastingHandler ] [Conjure Drink  ] castbar input 54ms -154.4939ms

> [00:00:27:579 I] [CastingHandler ] [Fireball       ] castbar input 93ms -122.7941ms
> [00:00:27:827 I] [CastingHandler ] [Fireball       ] castbar input 91ms -94.9582ms
> [00:00:29:376 I] [CastingHandler ] [Fireball       ] castbar input 61ms -108.2456ms
> [00:00:29:576 I] [CastingHandler ] [Fireball       ] castbar input 91ms -107.958ms

> [00:00:38:243 I] [CastingHandler ] [Frostbolt      ] instant input 61ms ERR_SPELL_FAILED_ANOTHER_IN_PROGRESS -93.9927ms
> [00:00:38:430 I] [CastingHandler ] [Frostbolt      ] instant input 80ms ERR_SPELL_FAILED_ANOTHER_IN_PROGRESS -106.6174ms

What you should look at is the last number, all of these lines last timing number are all **negative** example `-107.958ms`. That means the Conditions to await to detect the keypress from the bot does not properly propagated into the game. The C# backend unable to detect the keypress event in-game. In other words the in-game addon does not provide feedback to the c# backend.

All i can say is the Frame Configuration was successful, however the systems are unable to communicate properly. Usually what resolves the issue is deleting the `frame_config.json` file and do a Frame Configuration.

To resolve these negative numbers issue suggest to do [5. BlazorServer Configuration process](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#5-blazorserver-configuration-process) also be sure to follow these as well, part of the validations:
* [Guidance for good DataFrame](https://github.com/Xian55/WowClassicGrindBot/wiki/Guidance-for-good-DataFrame)
* [Validating FrameConfiguration](https://github.com/Xian55/WowClassicGrindBot/wiki/Validating-FrameConfiguration)

**Comment by cppbeliever** [comment]
@Xian55 

My version is Wrath of the Lich King, but the V3 navigation file I use is Vanilla + TBC + Wrath + Cataclysm - work in progress. This should be the reason why the character cannot be resurrected normally after death. Thank you.
