### ISSUE TITLE
make drink/food problem

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#603]
My goal is to make drinks(Just once) when the number of drinks in the pack is less than 20, but my config keeps making drinks (even if the pack is full), what's the problem? Thank you.

    "Adhoc": {
    "Sequence": [
	  {
        "Name": "Conjure Drink",
        "Key": "112",
		"Cost":5,
        "HasCastBar": true,
        "Requirement": "!BagItem:Item_Conjure_Drink:20",
        "AfterCastWaitCastbar": true,
        "AfterCastWaitBag": true
      }
    ]
  }

**Comment by Xian55** [comment]
Hello, every time when you going to open an issue, i'm going to be always asking for logs, and **Not partial logs**, but all of them, you have to understand i have to see everything in order to draw conclusion.

I would be really grateful if you could follow the [existing template for filling out bug reports](https://github.com/Xian55/WowClassicGrindBot/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml).

It may look outdated, however there's everything which is required in order i can start meaningfully the investigation.

Thank you, have a nice day!

**Comment by cppbeliever** [comment]
> Hello, every time when you going to open an issue, i'm going to be always asking for logs, and **Not partial logs**, but all of them, you have to understand i have to see everything in order to draw conclusion.
> 
> I would be really grateful if you could follow the [existing template for filling out bug reports](https://github.com/Xian55/WowClassicGrindBot/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml).
> 
> It may look outdated, however there's everything which is required in order i can start meaningfully the investigation.
> 
> Thank you, have a nice day!

Sorry, I will correct my mistake later.
Regarding this issue, I will upload all the logs as you requested, and I will temporarily close this issue. Thank you for your reply.
