### ISSUE TITLE
if (rarity == 0 or rarity == 1) and itemPrice ~= 0 then  //Cannot sell white quality items

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#605]
### Description

I want to sell all white quality items in the bag, so I modified the SellJunkFunc function (the condition for judging the rarity of the item). The modification is as follows:
From:
if (rarity == 0) and itemPrice ~= 0 then
To:
if (rarity == 0 or rarity == 1) and itemPrice ~= 0 then
However, all white quality items in the bag still exist and are not sold to the merchant, while gray items can be successfully sold to the merchant.
why?

The directory of the SellJunk.Lua file I modified is as follows:
1.WowClassicGrindBot-dev\Addons\DataToColor\SellJunk.lua
2.WowClassicGrindBot-dev\BlazorServer\Addons\DataToColor\SellJunk.lua
3.WowClassicGrindBot-dev\BlazorServer\bin\Release\net8.0\Addons\DataToColor\SellJunk.lua

thanks!

### Addon Version

1.7.57

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

no

### Screenshots

![notsell](https://github.com/Xian55/WowClassicGrindBot/assets/115885361/436130e4-957e-4986-92c1-dc592a4f3842)

### Logs

Blazor Server Log:
[out20240708_003.log](https://github.com/user-attachments/files/16125680/out20240708_003.log)

HeadLessServer Log:
[headless_out20240708.log](https://github.com/user-attachments/files/16125686/headless_out20240708.log)

BindPad macro(Tested without any problem):
/tar 雅尼·铁心
/run SellJunkFunc()

**Comment by Xian55** [comment]
> The directory of the SellJunk.Lua file I modified is as follows:
> 1.WowClassicGrindBot-dev\Addons\DataToColor\SellJunk.lua
> 2.WowClassicGrindBot-dev\BlazorServer\Addons\DataToColor\SellJunk.lua
> 3.WowClassicGrindBot-dev\BlazorServer\bin\Release\net8.0\Addons\DataToColor\SellJunk.lua

Just because you edited these lua file outside of the world of warcraft installation folder it wont end up magically in there(unless you are using [symlink](https://en.wikipedia.org/wiki/Symbolic_link)).

You have to reinstall the custom addon via the BlazorServer (Addon Config tab) and after a `/reload` the functionality should work.

---

On the other hand this is not a `bug` but rather a feature request, which i would not accept by default.

Selling white items might be risky and can end up unexpected consequences.

If you wish to do such modification you can do it on your end, the source code is open.

**Comment by cppbeliever** [comment]
@Xian55 
thanks for your help!
