### ISSUE TITLE
The character cannot automatically adjust the direction(turn around) ,when the monster is about to die, run away.

### ISSUE THREAD

**Issue by cppbeliever** [Xian55/WowClassicGrindBot#607]
### Description

**Question1:** 
When attacking the monster, my character is facing the monster. When the monster is about to die, it escapes (towards my character's back). At this time, my character does not adjust the direction (turn around), which makes my character unable to attack.

**Question2:**
I first deleted frame_config.json through Frame config and then re-executed it strictly according to the rules (5. BlazorServer Configuration process), but the negative number problem still exists ([CastingHandler] [Fireball] castbar input 61ms -94.1147ms)

### Addon Version

1.7.57

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

no

### Screenshots

![not_turn](https://github.com/Xian55/WowClassicGrindBot/assets/115885361/83b43544-c122-4246-8dcd-fa0be9b2c978)

### Logs

blazor server:
[out20240708_009.log](https://github.com/user-attachments/files/16132337/out20240708_009.log)
[out20240708_010.log](https://github.com/user-attachments/files/16132338/out20240708_010.log)
[out20240709.log](https://github.com/user-attachments/files/16132339/out20240709.log)

HeadBlessServer:
[headless_out20240708.log](https://github.com/user-attachments/files/16132351/headless_out20240708.log)
[headless_out20240709.log](https://github.com/user-attachments/files/16132352/headless_out20240709.log)

**Comment by Xian55** [comment]
Hello.

Are you sure you set all of the mentioned [settings](https://github.com/Xian55/WowClassicGrindBot?tab=readme-ov-file#8-configure-the-wow-client---interface-options) ?

Especially the `Enable Interact Key` is really important by default it is bind to the `i` key which is sadly bound by default Looking for Group keybind so be sure to override it.

Sadly since the 
> [CastingHandler] [Fireball] castbar input 61ms -94.1147ms

Issue still exists, the application cannot reach to point to correct player direction, since it cannot read the feedback from the game.

In the past i ran into weird issues, especially when i upgraded my primary monitor to 4k. Then the game did a factory reset setting for the graphics, as a side effect it enabled **V-Sync**. 

**V-Sync** must be turned off, it introduces soo much latency that many many weird issues start to happen. If you want to limit your FPS i suggest either to use Riva Tuner statistics server which is the best for this purpose or just use the in-game frame limiter to 60fps. I've usually tested features with 90fps, but it works flawlessly from 8fps - 144fps. Having stable frame rate and frame time also helps out!

Since you attached an image, where i can see overlay applications  running, you might want to disable these.
![image](https://github.com/Xian55/WowClassicGrindBot/assets/367101/143a672b-92cf-42e1-966e-b1bebb740831)

**Comment by cppbeliever** [comment]
@Xian55  Hello.

1.I made sure the keys were set according to this rule ( Configure the Wow Client - Interface Options ), I checked it twice.
2.I made sure "Enable Interact Key" is bind to the key:I 
3.I turned off the vertical sync function.
4.The highest resolution of the laptop I'm using now is 1920*1080, and this is also the setting in the game (System > Render Scale: 100% 1920*1080).I don't have any other monitors connected to my laptop.
5.Graphics->Maximum foreground frame rate switch: Disable
   Graphics->Maximum background frame rate: Enable 30FPS
   Graphics->Target frame rate:Enable 60FPS
6.I uninstalled the software (the one on the right in the picture above). The software on the left is an input method. Do I need to uninstall it as well? Does it mean that any overlay is not allowed?

**Comment by Xian55** [comment]
> 6.I uninstalled the software (the one on the right in the picture above). The software on the left is an input method. Do I need to uninstall it as well? Does it mean that any overlay is not allowed?

Well i did not requested to uninstall any of them, just **disable**, and so check if it makes a difference :)

The general issue with the overlay applications is that, they tend to use one of the corner of the screen potentially, partially covering the addon area.

There are other kinds of applications like f.lux which does post processing, which ends up on the final image, altering the final colors.

---

In the BlazorServer, there's a tab called "Raw Player Values" or something like that, where you can inspect what the c# backend reads from the addon realtime.

what you can do is for example in the mage, start casting `Conjure Muffin` spell, then quickly alt+tab and check what the `SpellBeingCast` value shows, it supposed to show the `SPELL_ID` which you can look up at wowhead.com.

https://www.wowhead.com/classic/spell=15063/frost-nova

**Comment by cppbeliever** [comment]
> > 6.I uninstalled the software (the one on the right in the picture above). The software on the left is an input method. Do I need to uninstall it as well? Does it mean that any overlay is not allowed?
> 
> Well i did not requested to uninstall any of them, just **disable**, and so check if it makes a difference :)
> 
> The general issue with the overlay applications is that, they tend to use one of the corner of the screen potentially, partially covering the addon area.
> 
> There are other kinds of applications like f.lux which does post processing, which ends up on the final image, altering the final colors.
> 
> In the BlazorServer, there's a tab called "Raw Player Values" or something like that, where you can inspect what the c# backend reads from the addon realtime.
> 
> what you can do is for example in the mage, start casting `Conjure Muffin` spell, then quickly alt+tab and check what the `SpellBeingCast` value shows, it supposed to show the `SPELL_ID` which you can look up at wowhead.com.
> 
> https://www.wowhead.com/classic/spell=15063/frost-nova

thanks.
