### ISSUE TITLE
Is the way you send inputs undetectable?

### ISSUE THREAD

**Issue by LeonardoFBR** [Xian55/WowClassicGrindBot#611]
I have seen that they use “Interception”, drivers or even hardware to make mouse and keyboard inputs undetectable.

**Comment by Xian55** [comment]
Hello.

> Is the way you send inputs undetectable?

No, i don't think so. Most of the low level input logic is implemented in [InputWindowsNative](https://github.com/Xian55/WowClassicGrindBot/blob/dev/Game/Input/InputWindowsNative.cs#L16), which boils down to WinAPI call [PostMessage](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postmessagea).

At higher level i'm using [randomization time](https://github.com/Xian55/WowClassicGrindBot/blob/db048b61af2c3c4f5c983046a85715ef09149359/Game/Input/InputWindowsNative.cs#L24C17-L24C26) technique in order to avoid static [key down press durations](https://github.com/Xian55/WowClassicGrindBot/blob/db048b61af2c3c4f5c983046a85715ef09149359/Game/Input/InputDuration.cs#L4).

---

In the past i've experimented implementing a hook, which overrides the [LLMHF_INJECTED](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-msllhookstruct) flag to 0, however it was unreliable due to the fact that it wasn't always loaded first in the chain, i deemed to be not worth the effort from my side. I've tried to use the following [github repo](https://github.com/TetteDev/LowLevelMouseHook-Example)
