### ISSUE TITLE
Bot usually get stuck when pulling target

### ISSUE THREAD

**Issue by Billdong1997** [Xian55/WowClassicGrindBot#98]
If there is an obstacle between character and mob, it will get stuck. The target should be cleared if the pull process is too long

I notice that there is such a code in `PullTargetGoal`,  why is it annotated and not used?
```
/* 
if ((DateTime.Now - PullStartTime).TotalSeconds > 30)
{
//await wowProcess.KeyPress(ConsoleKey.F3, 50); // clear target
await wowProcess.TapClearTarget();
await this.wowProcess.KeyPress(ConsoleKey.RightArrow, 1000, "Turn after pull timeout");
return; 
 } 
*/
```

**Comment by Xian55** [comment]
Hey thanks for reaching out. 

Back in a day, when i worked on some other issue i wanted to eliminate all the cases when the  `TapClearTarget()` is called for no reason. Which were caused to lose target middle of the fight if i recall correctly, the target moving out of combat range because of low health flee(humanoids) and suddenly the player started turning and kept stuck in that location.

The root issue of that case most likely due incorrectly not resetting the `PullStartTime` due body pulling.
